# Get all users
####
GET http://localhost:5000/users
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MDVlOThiLTc2NzUtNDFiYi1hYjViLWRkNDBjYjUxODc2MSIsInVzZXJuYW1lIjoiWW91bmdib3kiLCJlbWFpbCI6InlvdW5nYm95QGV4YW1wbGUuY29tIiwiYWJvdXQiOiJJIGFtIGEgc29mdHdhcmUgZGV2ZWxvcGVyIHdpdGggb3ZlciA2IHllYXJzIG9mIGV4cGlyaWVuY2UgYW5kICBoYXZlIHdvcmtlZCBpbiBtb3JlIHRoYXQgMTAgcHJvamVjdHMiLCJyb2xlIjoiYWRtaW4iLCJ0aXRsZSI6IlNvZnR3YXJlIERldmVsb3BlciIsImVtYWlsU2VudCI6MSwiaWF0IjoxNjg3Mzc0NjgzLCJleHAiOjE2ODc3MzQ2ODN9.LePqbvG0IACNPvSV3mk4rQ6JnsUaVF9qwb1D_-1jy6Y

# Get a user by id
#####
GET http://localhost:5000/users/6605e98b-7675-41bb-ab5b-dd40cb518761

# get a user by email
#####
GET http://localhost:5000/users/email/alexmaingi@example.com

# delete a user
#####
DELETE  http://localhost:5000/users/e7e1147d-4166-4394-be75-26ff3373f09f
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFjYWJlNDA5LTRiZWYtNGE2MC1hNGZmLTIzMzQxNjkwOTU5ZiIsInVzZXJuYW1lIjoiQWxleG1haW5naSIsImVtYWlsIjoibUBnbWFpbC5jb20iLCJhYm91dCI6bnVsbCwicm9sZSI6InVzZXIiLCJ0aXRsZSI6bnVsbCwiZW1haWxTZW50IjpudWxsLCJpYXQiOjE2ODczNzQ5MTYsImV4cCI6MTY4NzczNDkxNn0.q45nz0HTich3DUVC2rCmj_Y-B2zUAyHXyq2yjMM-yVk


# add a user
#####
POST http://localhost:5000/users
Content-Type:  application/json

{
   "username":"Maingi" ,
   "email":"maingi@gmail.com",
   "password":"alexmaingi"
}

# log in admin
#####
POST http://localhost:5000/users/login
Content-Type:  application/json

{
     "email":"maingi@gmail.com",
   "password":"alexmaingi"

}


# log in a user
#####
POST http://localhost:5000/users/login
Content-Type:  application/json

{
    "email":"m@gmail.com",
   "password":"alexmaingi"
}


# update a user
#####
PUT  http://localhost:5000/users/6605e98b-7675-41bb-ab5b-dd40cb518761
Content-Type:  application/json

{
   "username":"Youngboy" ,
   "email":"youngboy@example.com",
   "about":"I am a software developer with over 6 years of expirience and  have worked in more that 10 projects",
   "title":"Software Developer"
  
}



# add question
#####
POST  http://localhost:5000/questions/acabe409-4bef-4a60-a4ff-23341690959f
Content-Type:  application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MDVlOThiLTc2NzUtNDFiYi1hYjViLWRkNDBjYjUxODc2MSIsInVzZXJuYW1lIjoiWW91bmdib3kiLCJlbWFpbCI6InlvdW5nYm95QGV4YW1wbGUuY29tIiwiYWJvdXQiOiJJIGFtIGEgc29mdHdhcmUgZGV2ZWxvcGVyIHdpdGggb3ZlciA2IHllYXJzIG9mIGV4cGlyaWVuY2UgYW5kICBoYXZlIHdvcmtlZCBpbiBtb3JlIHRoYXQgMTAgcHJvamVjdHMiLCJyb2xlIjoiYWRtaW4iLCJ0aXRsZSI6IlNvZnR3YXJlIERldmVsb3BlciIsImVtYWlsU2VudCI6MSwiaWF0IjoxNjg3Mzc0NjgzLCJleHAiOjE2ODc3MzQ2ODN9.LePqbvG0IACNPvSV3mk4rQ6JnsUaVF9qwb1D_-1jy6Y


{
   "title":"merge branches" ,
   "body":"I am a have worked in more that 10 projects",
   "tags":[{"tagname":"#Git"}]
  
}



//get all questions
###
GET http://localhost:5000/questions?pageNumber=1&pageSize=3
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFjYWJlNDA5LTRiZWYtNGE2MC1hNGZmLTIzMzQxNjkwOTU5ZiIsInVzZXJuYW1lIjoiQWxleG1haW5naSIsImVtYWlsIjoibUBnbWFpbC5jb20iLCJhYm91dCI6bnVsbCwicm9sZSI6InVzZXIiLCJ0aXRsZSI6bnVsbCwiZW1haWxTZW50IjpudWxsLCJpYXQiOjE2ODczNzQ5MTYsImV4cCI6MTY4NzczNDkxNn0.q45nz0HTich3DUVC2rCmj_Y-B2zUAyHXyq2yjMM-yVk



# get questions by user id
#####
GET   http://localhost:5000/questions/d060abd2-0f12-4616-888d-012ee54104e7



//get one question
###
GET http://localhost:5000/questions/question/1e395902-fc4a-4dd4-bb8d-17805cc81e08
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFjYWJlNDA5LTRiZWYtNGE2MC1hNGZmLTIzMzQxNjkwOTU5ZiIsInVzZXJuYW1lIjoiQWxleG1haW5naSIsImVtYWlsIjoibUBnbWFpbC5jb20iLCJhYm91dCI6bnVsbCwicm9sZSI6InVzZXIiLCJ0aXRsZSI6bnVsbCwiZW1haWxTZW50IjpudWxsLCJpYXQiOjE2ODczNzQ5MTYsImV4cCI6MTY4NzczNDkxNn0.q45nz0HTich3DUVC2rCmj_Y-B2zUAyHXyq2yjMM-yVk



# delete a question
#####
DELETE http://localhost:5000/questions/delete/19767810-8d37-4074-9729-172d4767acfb
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MDVlOThiLTc2NzUtNDFiYi1hYjViLWRkNDBjYjUxODc2MSIsInVzZXJuYW1lIjoiWW91bmdib3kiLCJlbWFpbCI6InlvdW5nYm95QGV4YW1wbGUuY29tIiwiYWJvdXQiOiJJIGFtIGEgc29mdHdhcmUgZGV2ZWxvcGVyIHdpdGggb3ZlciA2IHllYXJzIG9mIGV4cGlyaWVuY2UgYW5kICBoYXZlIHdvcmtlZCBpbiBtb3JlIHRoYXQgMTAgcHJvamVjdHMiLCJyb2xlIjoiYWRtaW4iLCJ0aXRsZSI6IlNvZnR3YXJlIERldmVsb3BlciIsImVtYWlsU2VudCI6MSwiaWF0IjoxNjg3Mzc1MjAwLCJleHAiOjE2ODc3MzUyMDB9.u46C7Gv-AZU3sFzqGmjnHnqcHSG5qj93dq9BUKC4Lgg


//update question
###
PUT http://localhost:5000/questions/update/d3d426c4-954c-4bea-80e6-a4a0332e540a/d060abd2-0f12-4616-888d-012ee54104e7
Content-Type:  application/json

{
    "title":" question", 
   "body":"a update" ,
   "tags":[{"tagname":"React js"}]
   
   }




# POST answer
####
POST http://localhost:5000/answers/1e395902-fc4a-4dd4-bb8d-17805cc81e08/8961d036-ef55-47e1-b807-5c86929bbc27
Content-Type:  application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFjYWJlNDA5LTRiZWYtNGE2MC1hNGZmLTIzMzQxNjkwOTU5ZiIsInVzZXJuYW1lIjoiQWxleG1haW5naSIsImVtYWlsIjoibUBnbWFpbC5jb20iLCJhYm91dCI6bnVsbCwicm9sZSI6InVzZXIiLCJ0aXRsZSI6bnVsbCwiZW1haWxTZW50IjpudWxsLCJpYXQiOjE2ODczNzQ5MTYsImV4cCI6MTY4NzczNDkxNn0.q45nz0HTich3DUVC2rCmj_Y-B2zUAyHXyq2yjMM-yVk


{
    "body": "the looong answer pt 5 "
}



# get answers
####
GET  http://localhost:5000/answers/07d6674b-cc31-443b-aa07-2d80798deacc



# mark as acepted
####
POST http://localhost:5000/answers/answer/accepted/83610b71-2704-4c6c-9b30-7241c3959fd2






# add comment
######
POST http://localhost:5000/comments/3e4f4260-4562-430f-bea8-83c01c4d3ee7/d060abd2-0f12-4616-888d-012ee54104e7
Content-Type:  application/json

{
    "body": "the comment number 2"
   
   }


   # get comment by question id
######
GET  http://localhost:5000/comments/3e4f4260-4562-430f-bea8-83c01c4d3ee7




# upvote
######
POST http://localhost:5000/votes/upvote/86279d7c-24c1-4086-b823-91389af1acc1/d060abd2-0f12-4616-888d-012ee54104e7



# upvote
######
POST http://localhost:5000/votes/downvote/86279d7c-24c1-4086-b823-91389af1acc1/461d514f-3ec2-4e8c-82a9-0edff0d75302
